# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_animation', models.CharField(blank=True, choices=[('bounce', 'Bounce'), ('flash', 'Flash'), ('pulse', 'Pulse'), ('rubberBand', 'Rubber Band'), ('shake', 'Shake'), ('headShake', 'Head Shake'), ('swing', 'Swing'), ('tada', 'Tada'), ('wobble', 'Wobble'), ('jello', 'Jello'), ('bounceIn', 'Bounce In'), ('bounceInDown', 'Bounce In Down'), ('bounceInLeft', 'Bounce In Left'), ('bounceInRight', 'Bounce In Right'), ('bounceInUp', 'Bounce In Up'), ('bounceOut', 'Bounce Out'), ('bounceOutDown', 'Bounce Out Down'), ('bounceOutLeft', 'Bounce Out Left'), ('bounceOutRight', 'Bounce Out Right'), ('bounceOutUp', 'Bounce Out Up'), ('fadeIn', 'Fade In'), ('fadeInDown', 'Fade In Down'), ('fadeInDownBig', 'Fade In Down Big'), ('fadeInLeft', 'Fade In Left'), ('fadeInLeftBig', 'Fade In Left Big'), ('fadeInRight', 'Fade In Right'), ('fadeInRightBig', 'Fade In Right Big'), ('fadeInUp', 'Fade In Up'), ('fadeInUpBig', 'Fade In Up Big'), ('fadeOut', 'Fade Out'), ('fadeOutDown', 'Fade Out Down'), ('fadeOutDownBig', 'Fade Out Down Big'), ('fadeOutLeft', 'Fade Out Left'), ('fadeOutLeftBig', 'Fade Out Left Big'), ('fadeOutRight', 'Fade Out Right'), ('fadeOutRightBig', 'Fade Out Right Big'), ('fadeOutUp', 'Fade Out Up'), ('fadeOutUpBig', 'Fade Out Up Big'), ('flipInX', 'Flip In X'), ('flipInY', 'Flip In Y'), ('flipOutX', 'Flip Out X'), ('flipOutY', 'Flip Out Y'), ('lightspeedIn', 'Lightspeed In'), ('lightspeedOut', 'Lightspeed Out'), ('rotateIn', 'Rotate In'), ('rotateInDownLeft', 'Rotate In Down Left'), ('rotateInDownRight', 'Rotate In Down Right'), ('rotateInUpLeft', 'Rotate In Up Left'), ('rotateInUpRight', 'Rotate In Up Right'), ('rotateOut', 'Rotate Out'), ('rotateOutDownLeft', 'Rotate Out Down Left'), ('rotateOutDownRight', 'Rotate Out Down Right'), ('rotateOutUpLeft', 'Rotate Out Up Left'), ('rotateOutUpRight', 'Rotate Out Up Right'), ('hinge', 'Hinge'), ('rollIn', 'Roll In'), ('rollOut', 'Roll Out'), ('zoomIn', 'Zoom In'), ('zoomInDown', 'Zoom In Down'), ('zoomInLeft', 'Zoom In Left'), ('zoomInRight', 'Zoom In Right'), ('zoomInUp', 'Zoom In Up'), ('zoomOut', 'Zoom Out'), ('zoomOutDown', 'Zoom Out Down'), ('zoomOutLeft', 'Zoom Out Left'), ('zoomOutRight', 'Zoom Out Right'), ('zoomOutUp', 'Zoom Out Up'), ('slideInDown', 'Slide In Down'), ('slideInLeft', 'Slide In Left'), ('slideInRight', 'Slide In Right'), ('slideInUp', 'Slide In Up'), ('slideOutDown', 'Slide Out Down'), ('slideOutLeft', 'Slide Out Left'), ('slideOutRight', 'Slide Out Right'), ('slideOutUp', 'Slide Out Up')], max_length=32, null=True)),
                ('exit_animation', models.CharField(blank=True, choices=[('bounce', 'Bounce'), ('flash', 'Flash'), ('pulse', 'Pulse'), ('rubberBand', 'Rubber Band'), ('shake', 'Shake'), ('headShake', 'Head Shake'), ('swing', 'Swing'), ('tada', 'Tada'), ('wobble', 'Wobble'), ('jello', 'Jello'), ('bounceIn', 'Bounce In'), ('bounceInDown', 'Bounce In Down'), ('bounceInLeft', 'Bounce In Left'), ('bounceInRight', 'Bounce In Right'), ('bounceInUp', 'Bounce In Up'), ('bounceOut', 'Bounce Out'), ('bounceOutDown', 'Bounce Out Down'), ('bounceOutLeft', 'Bounce Out Left'), ('bounceOutRight', 'Bounce Out Right'), ('bounceOutUp', 'Bounce Out Up'), ('fadeIn', 'Fade In'), ('fadeInDown', 'Fade In Down'), ('fadeInDownBig', 'Fade In Down Big'), ('fadeInLeft', 'Fade In Left'), ('fadeInLeftBig', 'Fade In Left Big'), ('fadeInRight', 'Fade In Right'), ('fadeInRightBig', 'Fade In Right Big'), ('fadeInUp', 'Fade In Up'), ('fadeInUpBig', 'Fade In Up Big'), ('fadeOut', 'Fade Out'), ('fadeOutDown', 'Fade Out Down'), ('fadeOutDownBig', 'Fade Out Down Big'), ('fadeOutLeft', 'Fade Out Left'), ('fadeOutLeftBig', 'Fade Out Left Big'), ('fadeOutRight', 'Fade Out Right'), ('fadeOutRightBig', 'Fade Out Right Big'), ('fadeOutUp', 'Fade Out Up'), ('fadeOutUpBig', 'Fade Out Up Big'), ('flipInX', 'Flip In X'), ('flipInY', 'Flip In Y'), ('flipOutX', 'Flip Out X'), ('flipOutY', 'Flip Out Y'), ('lightspeedIn', 'Lightspeed In'), ('lightspeedOut', 'Lightspeed Out'), ('rotateIn', 'Rotate In'), ('rotateInDownLeft', 'Rotate In Down Left'), ('rotateInDownRight', 'Rotate In Down Right'), ('rotateInUpLeft', 'Rotate In Up Left'), ('rotateInUpRight', 'Rotate In Up Right'), ('rotateOut', 'Rotate Out'), ('rotateOutDownLeft', 'Rotate Out Down Left'), ('rotateOutDownRight', 'Rotate Out Down Right'), ('rotateOutUpLeft', 'Rotate Out Up Left'), ('rotateOutUpRight', 'Rotate Out Up Right'), ('hinge', 'Hinge'), ('rollIn', 'Roll In'), ('rollOut', 'Roll Out'), ('zoomIn', 'Zoom In'), ('zoomInDown', 'Zoom In Down'), ('zoomInLeft', 'Zoom In Left'), ('zoomInRight', 'Zoom In Right'), ('zoomInUp', 'Zoom In Up'), ('zoomOut', 'Zoom Out'), ('zoomOutDown', 'Zoom Out Down'), ('zoomOutLeft', 'Zoom Out Left'), ('zoomOutRight', 'Zoom Out Right'), ('zoomOutUp', 'Zoom Out Up'), ('slideInDown', 'Slide In Down'), ('slideInLeft', 'Slide In Left'), ('slideInRight', 'Slide In Right'), ('slideInUp', 'Slide In Up'), ('slideOutDown', 'Slide Out Down'), ('slideOutLeft', 'Slide Out Left'), ('slideOutRight', 'Slide Out Right'), ('slideOutUp', 'Slide Out Up')], max_length=32, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(blank=True, max_length=255, null=True)),
                ('family_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('family_name', 'given_name'),
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_animation', models.CharField(blank=True, choices=[('bounce', 'Bounce'), ('flash', 'Flash'), ('pulse', 'Pulse'), ('rubberBand', 'Rubber Band'), ('shake', 'Shake'), ('headShake', 'Head Shake'), ('swing', 'Swing'), ('tada', 'Tada'), ('wobble', 'Wobble'), ('jello', 'Jello'), ('bounceIn', 'Bounce In'), ('bounceInDown', 'Bounce In Down'), ('bounceInLeft', 'Bounce In Left'), ('bounceInRight', 'Bounce In Right'), ('bounceInUp', 'Bounce In Up'), ('bounceOut', 'Bounce Out'), ('bounceOutDown', 'Bounce Out Down'), ('bounceOutLeft', 'Bounce Out Left'), ('bounceOutRight', 'Bounce Out Right'), ('bounceOutUp', 'Bounce Out Up'), ('fadeIn', 'Fade In'), ('fadeInDown', 'Fade In Down'), ('fadeInDownBig', 'Fade In Down Big'), ('fadeInLeft', 'Fade In Left'), ('fadeInLeftBig', 'Fade In Left Big'), ('fadeInRight', 'Fade In Right'), ('fadeInRightBig', 'Fade In Right Big'), ('fadeInUp', 'Fade In Up'), ('fadeInUpBig', 'Fade In Up Big'), ('fadeOut', 'Fade Out'), ('fadeOutDown', 'Fade Out Down'), ('fadeOutDownBig', 'Fade Out Down Big'), ('fadeOutLeft', 'Fade Out Left'), ('fadeOutLeftBig', 'Fade Out Left Big'), ('fadeOutRight', 'Fade Out Right'), ('fadeOutRightBig', 'Fade Out Right Big'), ('fadeOutUp', 'Fade Out Up'), ('fadeOutUpBig', 'Fade Out Up Big'), ('flipInX', 'Flip In X'), ('flipInY', 'Flip In Y'), ('flipOutX', 'Flip Out X'), ('flipOutY', 'Flip Out Y'), ('lightspeedIn', 'Lightspeed In'), ('lightspeedOut', 'Lightspeed Out'), ('rotateIn', 'Rotate In'), ('rotateInDownLeft', 'Rotate In Down Left'), ('rotateInDownRight', 'Rotate In Down Right'), ('rotateInUpLeft', 'Rotate In Up Left'), ('rotateInUpRight', 'Rotate In Up Right'), ('rotateOut', 'Rotate Out'), ('rotateOutDownLeft', 'Rotate Out Down Left'), ('rotateOutDownRight', 'Rotate Out Down Right'), ('rotateOutUpLeft', 'Rotate Out Up Left'), ('rotateOutUpRight', 'Rotate Out Up Right'), ('hinge', 'Hinge'), ('rollIn', 'Roll In'), ('rollOut', 'Roll Out'), ('zoomIn', 'Zoom In'), ('zoomInDown', 'Zoom In Down'), ('zoomInLeft', 'Zoom In Left'), ('zoomInRight', 'Zoom In Right'), ('zoomInUp', 'Zoom In Up'), ('zoomOut', 'Zoom Out'), ('zoomOutDown', 'Zoom Out Down'), ('zoomOutLeft', 'Zoom Out Left'), ('zoomOutRight', 'Zoom Out Right'), ('zoomOutUp', 'Zoom Out Up'), ('slideInDown', 'Slide In Down'), ('slideInLeft', 'Slide In Left'), ('slideInRight', 'Slide In Right'), ('slideInUp', 'Slide In Up'), ('slideOutDown', 'Slide Out Down'), ('slideOutLeft', 'Slide Out Left'), ('slideOutRight', 'Slide Out Right'), ('slideOutUp', 'Slide Out Up')], max_length=32, null=True)),
                ('exit_animation', models.CharField(blank=True, choices=[('bounce', 'Bounce'), ('flash', 'Flash'), ('pulse', 'Pulse'), ('rubberBand', 'Rubber Band'), ('shake', 'Shake'), ('headShake', 'Head Shake'), ('swing', 'Swing'), ('tada', 'Tada'), ('wobble', 'Wobble'), ('jello', 'Jello'), ('bounceIn', 'Bounce In'), ('bounceInDown', 'Bounce In Down'), ('bounceInLeft', 'Bounce In Left'), ('bounceInRight', 'Bounce In Right'), ('bounceInUp', 'Bounce In Up'), ('bounceOut', 'Bounce Out'), ('bounceOutDown', 'Bounce Out Down'), ('bounceOutLeft', 'Bounce Out Left'), ('bounceOutRight', 'Bounce Out Right'), ('bounceOutUp', 'Bounce Out Up'), ('fadeIn', 'Fade In'), ('fadeInDown', 'Fade In Down'), ('fadeInDownBig', 'Fade In Down Big'), ('fadeInLeft', 'Fade In Left'), ('fadeInLeftBig', 'Fade In Left Big'), ('fadeInRight', 'Fade In Right'), ('fadeInRightBig', 'Fade In Right Big'), ('fadeInUp', 'Fade In Up'), ('fadeInUpBig', 'Fade In Up Big'), ('fadeOut', 'Fade Out'), ('fadeOutDown', 'Fade Out Down'), ('fadeOutDownBig', 'Fade Out Down Big'), ('fadeOutLeft', 'Fade Out Left'), ('fadeOutLeftBig', 'Fade Out Left Big'), ('fadeOutRight', 'Fade Out Right'), ('fadeOutRightBig', 'Fade Out Right Big'), ('fadeOutUp', 'Fade Out Up'), ('fadeOutUpBig', 'Fade Out Up Big'), ('flipInX', 'Flip In X'), ('flipInY', 'Flip In Y'), ('flipOutX', 'Flip Out X'), ('flipOutY', 'Flip Out Y'), ('lightspeedIn', 'Lightspeed In'), ('lightspeedOut', 'Lightspeed Out'), ('rotateIn', 'Rotate In'), ('rotateInDownLeft', 'Rotate In Down Left'), ('rotateInDownRight', 'Rotate In Down Right'), ('rotateInUpLeft', 'Rotate In Up Left'), ('rotateInUpRight', 'Rotate In Up Right'), ('rotateOut', 'Rotate Out'), ('rotateOutDownLeft', 'Rotate Out Down Left'), ('rotateOutDownRight', 'Rotate Out Down Right'), ('rotateOutUpLeft', 'Rotate Out Up Left'), ('rotateOutUpRight', 'Rotate Out Up Right'), ('hinge', 'Hinge'), ('rollIn', 'Roll In'), ('rollOut', 'Roll Out'), ('zoomIn', 'Zoom In'), ('zoomInDown', 'Zoom In Down'), ('zoomInLeft', 'Zoom In Left'), ('zoomInRight', 'Zoom In Right'), ('zoomInUp', 'Zoom In Up'), ('zoomOut', 'Zoom Out'), ('zoomOutDown', 'Zoom Out Down'), ('zoomOutLeft', 'Zoom Out Left'), ('zoomOutRight', 'Zoom Out Right'), ('zoomOutUp', 'Zoom Out Up'), ('slideInDown', 'Slide In Down'), ('slideInLeft', 'Slide In Left'), ('slideInRight', 'Slide In Right'), ('slideInUp', 'Slide In Up'), ('slideOutDown', 'Slide Out Down'), ('slideOutLeft', 'Slide Out Left'), ('slideOutRight', 'Slide Out Right'), ('slideOutUp', 'Slide Out Up')], max_length=32, null=True)),
                ('headline', models.CharField(max_length=255)),
                ('ordinal', models.PositiveIntegerField(blank=True, db_index=True)),
                ('contributors', models.ManyToManyField(blank=True, through='django_credits.Contribution', to='django_credits.Contributor')),
            ],
            options={
                'ordering': ('ordinal',),
            },
        ),
        migrations.AddField(
            model_name='contribution',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_credits.Contributor'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_credits.Credit'),
        ),
    ]
